n_gpu: 4

data_loader:
  type: FeatureDataloader
  args:
    num_workers: 16
    batch_size: 16
    shuffle: false
    dataset_name: 'YouCook2'

    dataset_kwargs:
      data_path: './data/youcook/resnet/youcook_val.pkl'
      max_words: 20
      n_video_tokens: 12
      num_audio_STFT_frames: 768
      cut_clips: true
      n_clips: 6
      word2vec_path: './data/GoogleNews-vectors-negative300.bin'