n_gpu: 4

data_loader:
  type: FeatureDataloader
  args:
    num_workers: 16
    batch_size: 16
    shuffle: false
    dataset_name: 'YouCook2'

    dataset_kwargs:
      data_path: './data/youcook/resnet/youcook_val.pkl'
      data_path_2D: './data/youcook/clip/youcook_val.pkl'
      use_2D: True
      use_3D: False
      key_2d: 'clip'
      max_words: 20
      n_video_tokens: 72
      num_audio_STFT_frames: 4608
      word2vec_path: './data/GoogleNews-vectors-negative300.bin'